
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/usr/local/cuda/bin/"
      - "/home/ares/apps/python314/bin/"
      - "/home/ares/.mimocode/bin/"
      - "/home/ares/.local/bin/"
      - "/home/ares/.opencode/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/c/WINDOWS/system32/"
      - "/mnt/c/WINDOWS/"
      - "/mnt/c/WINDOWS/System32/Wbem/"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/WINDOWS/System32/OpenSSH/"
      - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "/mnt/e/apps/Bandizip/"
      - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "/mnt/e/Windows Kits/10/Windows Performance Toolkit/"
      - "/mnt/e/apps/Git/cmd/"
      - "/mnt/e/apps/cmake/bin/"
      - "/mnt/c/Users/GrayO/AppData/Local/Microsoft/WindowsApps/"
      - "/mnt/e/apps/Microsoft VS Code/bin/"
      - "/mnt/c/Users/GrayO/AppData/Local/Programs/Ollama/"
    searched_directories:
      - "/usr/local/cuda/bin/uname"
      - "/home/ares/apps/python314/bin/uname"
      - "/home/ares/.mimocode/bin/uname"
      - "/home/ares/.local/bin/uname"
      - "/home/ares/.opencode/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/usr/local/cuda/bin"
        - "/home/ares/apps/python314/bin"
        - "/home/ares/.mimocode/bin"
        - "/home/ares/.local/bin"
        - "/home/ares/.opencode/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR"
        - "/mnt/e/apps/Bandizip/"
        - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common"
        - "/mnt/e/Windows Kits/10/Windows Performance Toolkit/"
        - "/mnt/e/apps/Git/cmd"
        - "/mnt/e/apps/cmake/bin"
        - "/mnt/c/Users/GrayO/AppData/Local/Microsoft/WindowsApps"
        - "/mnt/e/apps/Microsoft VS Code/bin"
        - "/mnt/c/Users/GrayO/AppData/Local/Programs/Ollama"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.18.33.2-microsoft-standard-WSL2 - x86_64
...
